spring.application.name=fx-service

spring.datasource.url=jdbc:postgresql://localhost:5432/fx
spring.datasource.username=fx_user
spring.datasource.password=fx_password

spring.jpa.hibernate.ddl-auto=validate

spring.flyway.enabled=true

spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.cache.type=redis
spring.cache.redis.time-to-live=5m

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=when_authorized